title: ACL 2018
description: 56th Annual Meeting of the Association for Computational Linguistics
author: The ACL 2018 Organising Committee
# email: your-email@domain.com
# baseurl: "/acl2018-website"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-feed
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
key_dates:
  - date: "February 22nd, 2018"
    event: Submission Deadline (<a href="/call-for-papers/">Main Conference</a>)
  - date: "March 27th, 2018"
    event: Submission Deadline (<a href="/call-for-papers/sys-demos">System Demonstrations</a>)
  - date: "March 26th–28th, 2018"
    event: Author Response Period
  - date: "April 20th, 2018"
    event: Notification of Acceptance
  - date: "May 11th, 2018"
    event: Camera-ready Due
  - date: "July 15th, 2018"
    event: Tutorials
  - date: "July 16th–18th, 2018"
    event: Main Conference
  - date: "July 19th–20th, 2018"
    event: Workshops
permalink: pretty
collections:
  call_for_papers:
    output: true
    layout: cfp
    permalink: /call-for-papers/:name/
    title: Call for Papers
  attendees:
    output: true
    layout: attendees
    permalink: /attendees/:name/
    title: Attendees
  conference:
    output: true
    permalink: /conference/:name/
    title: Conference
defaults:
  - scope:
      path: ""
      type: call_for_papers
    values:
      layout: cfp
  - scope:
      path: ""
      type: attendees
    values:
      layout: attendees
top_nav:
  - url: /registration/
    title: Registration
  - url: /attendees/
    title: Attendees
  - url: /committee/
    title: Committee
  - url: /tutorials/
    title: Tutorials
  - url: /workshops/
    title: Workshops
  - url: /conference/accepted-papers
    title: Conference
  - url: /call-for-papers/
    title: CFP
  - url: /
    title: About


